apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    name: backend-svc
    app: guestbook-app
spec:
      ports:
      - port: 6379
        targetPort: 6379
      selector:
        name: backend-pod
        app: guestbook-app