apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: guestbook-app
spec:
      replicas: 1
      selector:
        matchLabels:
          name: backend-pod
          app: guestbook-app
      templates:
        metadata:
          name: backend-pod
          labels:
            name: backend-pod
            app: guestbook-app
        spec:
          containers:
          - name: redis-container
            image: redis