apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    app: guestbook-app
  spec:
    containers:
    - name: frontend-container
      image: kubernetes/guestbook:v2
      ports:
      - containerPort: 80