apiVersion: v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: guestbook-app
spec:
      replicas: 1
      selector:
        matchLabels:
          name: frontend-pod
          app: guestbook-app
      templates:
        metadata:
          name: frontend-pod
          labels:
            name: frontend-pod
            app: guestbook-app
        spec:
          containers:
          - name: frontend-container
            image: kubernetes/guestbook:v2
            ports:
            - containerPort: 80